#端口号
server:
  port: 55555

#datasource,数据库连接
spring:
  datasource:
    # mysql驱动
    driver-class-name: com.mysql.jdbc.Driver
    # 基本属性
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: root123

# mybatis 配置
mybatis:
  type-aliases-package: com.wass.hr.entity #配置映射实体类所在的包路径
  mapper-locations: classpath:com/*/mapper/*.xml
logging:
  level:
    com.wass.hr.mapper: debug #配置mapper.xml的所在的包路径
